<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-04T10:07:09 IST" name="Suite" finished-at="2023-01-04T10:08:26 IST" duration-ms="77426">
    <groups>
    </groups>
    <test started-at="2023-01-04T10:07:09 IST" name="Test" finished-at="2023-01-04T10:08:26 IST" duration-ms="77426">
      <class name="testController.TestController">
        <test-method is-config="true" signature="initBrowser()[pri:0, instance:testController.TestController@1da2cb77]" started-at="2023-01-04T10:07:09 IST" name="initBrowser" finished-at="2023-01-04T10:07:10 IST" duration-ms="1055" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initBrowser -->
        <test-method signature="TestCaseController()[pri:0, instance:testController.TestController@1da2cb77]" started-at="2023-01-04T10:07:10 IST" name="TestCaseController" finished-at="2023-01-04T10:08:26 IST" duration-ms="76319" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at excelReader.ExcelReader.getCellData(ExcelReader.java:64)
at testController.TestController.TestCaseController(TestController.java:73)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCaseController -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:testController.TestController@1da2cb77]" started-at="2023-01-04T10:08:26 IST" name="quitBrowser" finished-at="2023-01-04T10:08:26 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- testController.TestController -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
